openapi: 3.0.1
info:
  title: Zundoko Kiyoshi API
  version: "1.0"
servers:
- url: /
paths:
  /zundokos:
    get:
      tags:
      - zundoko
      operationId: getZundokos
      responses:
        200:
          description: dummy
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zundoko'
components:
  schemas:
    Zundoko:
      type: object
      properties:
        id:
          type: string
          format: uuid
        saidAt:
          type: string
          format: date-time
        word:
          type: string
          enum:
          - Zun
          - Doko
    Kiyoshi:
      type: object
      properties:
        id:
          type: string
          format: uuid
        saidAt:
          type: string
          format: date-time
        madeBy:
          type: string
          format: email
